### ISSUE TITLE
This package is not available for installation via bower as documented

### ISSUE THREAD

**Issue by grempe** [dchest/tweetnacl-util-js#1]
Despite what is in the README, installation of the newly extracted tweetnacl-util via bower fails since it does not appear to exist in the bower registry.

```
$ bower install tweetnacl-util
bower                        ENOTFOUND Package tweetnacl-util not found
```

Here is the search link on bower.io which shows this package is missing.

http://bower.io/search/?q=tweetnacl

It seems it was uploaded to npm repository.

https://www.npmjs.com/package/tweetnacl-util

**Comment by dchest** [comment]
Oops, thanks for noticing! I've published it.
