### ISSUE TITLE
Base64 functions are not URL safe

### ISSUE THREAD

**Issue by tuxxy** [dchest/tweetnacl-util-js#6]
As stated in the title, the base64 functions are not URL safe. As this is a javascript library, it would make sense for this to be URL safe by default or at least offer a URL safe alternative.

URL safe Base64 replaces the `+` and `/` characters with `-` and `_`, respectively.

**Comment by dchest** [comment]
Yup, just use `str.replace` to replace characters back and forth. This tiny library doesn't provide URL-safe or any other types of base64 encoding ;-)
