### ISSUE TITLE
Can't find variable: Buffer

### ISSUE THREAD

**Issue by pradeep1991singh** [dchest/tweetnacl-util-js#8]
Hi, there
I am on React-native app. I am using `nacl-util.decodeUTF8`.
and getting `Can't find variable: Buffer`.

any help is much appreciated.

**Comment by dchest** [comment]
Hi! React Native doesn't seem to have `atob` function, so tries `Buffer`, and React Native also doesn't have it. Please use some other encoding library, for example, my [@stablelib/utf8](https://www.stablelib.com/modules/_utf8_utf8_.html) (note that decode and encode operations are reversed) and [@stablelib/base64](https://www.stablelib.com/modules/_base64_base64_.html). (You can npm install them)
